### ISSUE TITLE
Crash when reading embedded font

### ISSUE THREAD

**Issue by sikachu** [pigoz/libass-ct#8] opened 2015-03-30 16:39 UTC
(Originally reported as mpv-player/mpv#1741)

When I run `mpv` that compiled against `libass-ct` HEAD (currently at af6c1d42c5a76a89697ecfddbba73102a28d3e1e) it would crash every time when it reaches this particular spot. @wm4 looked at the crash log earlier on mpv-player/mpv, and he suspected that it's because of embedded font loading issue.

Here's the log from stdout and crash log https://gist.github.com/sikachu/58e3ac1f9a79404d404c

```
$ mpv --version
mpv git-8fff125 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-03-30T15:49:36
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```

Please let me know if you need any more information from me. Thanks!

**Comment by pigoz** [comment] 2015-03-30 16:40
@sikachu it seems you are running an ancient version (probably due to the fact that homebrew doesn't update HEAD only formulas). Can you try to reinstall `libass-ct`? Otherwise I'll try to reproduce.

**Comment by sikachu** [comment] 2015-03-30 16:50
@pigoz actually, I was using the HEAD of `fonts` branch (as I ran `brew reinstall --HEAD libass-ct` followed by `brew reinstall --HEAD mpv`). I didn't see that Homebrew formula actually points to `fonts` branch.

So, yeah, I think I was on the latest version (so HEAD == 2510d739d4dff39923ce48c8b5402ba72947680d).

I can try reinstall everything again later after this encoding is done, but I'm 90% sure that I was on the right version ...

**Comment by pigoz** [comment] 2015-03-30 16:54
Trying to reproduce, the crash is in `[Coalgirls]_Tuskimonogatari_Playall_NoOPED_(1920x1080_Blu-ray_FLAC).mkv.mp4`?

**Comment by sikachu** [comment] 2015-03-30 17:01
Yes, that's correct. It should crash at that timestamp.

**Comment by sikachu** [comment] 2015-03-30 17:54
Just to be safe, I rebuilt `libass-ct` and `mpv` with `--HEAD` flag, and my `libass-ct` was indeed at 2510d739d4dff39923ce48c8b5402ba72947680d (HEAD of `fonts` branch).

Let me know if you need any help. I'm also on Rizon if you need to find me.

**Comment by jjgod** [comment] 2015-06-12 13:30
I can't reproduce this.

**Comment by pigoz** [comment] 2015-09-07 12:45
This was fixes in the official libass which merged the coretext code.

**Closed as completed by pigoz** 2015-09-07 12:45 UTC
